name: Deploy to Koyeb

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout kode
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Setup Java (sesuaikan versi jika perlu)
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      # 3. Build aplikasi (misalnya dengan Gradle)
      - name: Build Application
        run: ./gradlew clean bootJar

      # 4. Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/advshop:latest .

      # 5. Login ke Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 6. Push Docker image ke Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/advshop:latest

      # 7. Deploy ke Koyeb dengan memanggil API update service
      - name: Deploy to Koyeb
        run: |
          curl -X PATCH "https://app.koyeb.com/v1/services/${{ secrets.KOYEB_SERVICE_ID }}" \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "definition": {
                  "name": "advshop",
                  "routes": [{ "port": 8080 }],
                  "image": "'${{ secrets.DOCKERHUB_USERNAME }}'/advshop:latest"
                }
              }'
